language: elixir
matrix:
  include:
    - otp_release: 17.4
      elixir: 1.0
    - otp_release: 20.0
      elixir: 1.4
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq imagemagick